# NEBULA Multiverse Studio — Frontend Service | Architect: KNOCKS
apiVersion: v1
kind: Service
metadata:
  name: nebula-frontend-svc
  namespace: nebula
  labels:
    app: nebula-frontend
    app.kubernetes.io/part-of: nebula-multiverse-studio
    app.kubernetes.io/managed-by: knocks-architect
spec:
  type: ClusterIP
  selector:
    app: nebula-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
